### ISSUE TITLE
Upgrade android 5.1.1

### ISSUE THREAD

**Issue by nothing0126** [pjlantz/droidbox#24]
Hi! 
I have used DroidBox, it was ok! DroidBox used android 4.1.2 API 16, now I want to update to android 5.1.1 API 22, but cant find file ramdisk.img  and systme.img to root this version andorid 5.1.1. So,I have way to resuilt this my problem?
Thanks!

**Comment by q2dg** [comment]
Well...it seems this project is pretty abandoned
